server:
  port: 9500

spring:
  application:
    name: shopcloud.gateway

  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr: nacos-server
        namespace: cf9582db-449f-405f-9e30-152b6f26e895
        group: SHOPCLOUD_GROUP
        cluster-name: GatewayCluster
      username: zero
      password: mixin6879

    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user
          uri: lb://userservice.provider
          predicates:
            - Path=/users/**,/address/**
        - id: order
          uri: lb://orderservice.provider
          predicates:
            - Path=/orders/**
        - id: product
          uri: lb://productservice.provider
          predicates:
            - Path=/products/**,/categories/**,/banners/**
#            - After=2022-06-12T16:05:30+08:00[Asia/Shanghai]

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

mxzero:
  config:
    jwt:
      sign: mxzero
      site: mxzero.top
      issuer: zero
      secret: httpmxzerotop
      expire: 3600
      skips:
        - /users/token/create/**
        - /categories/**
        - /products/**
        - /banners/**
